- hosts: "{{ hosts }}"

  gather_facts: false

  tasks:

    - name: Obtain hostname
      sudo: yes
      action: setup filter=ansible_hostname

    - name: Check DNS
      sudo: no
      delegate_to: localhost
      action: shell dig +short "{{ ansible_hostname |lower }}".company.tld
      register: in_dns

    - name: Set in_dns in inventory to True
      sudo: no
      delegate_to: localhost
      action: shell psql inventory -c "UPDATE host_inventory SET in_dns=True WHERE hostname = '{{ inventory_hostname }}';"
      when: in_dns.stdout

    - name: Set in_dns in inventory to False
      sudo: no
      delegate_to: localhost
      action: shell psql inventory -c "UPDATE host_inventory SET in_dns=False WHERE hostname = '{{ inventory_hostname }}';"
      when: not in_dns.stdout
